services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: covoitme
      POSTGRES_PASSWORD: password
      POSTGRES_DB: covoitme
    ports:
      - "5432:5432"
    volumes:
      - covoitme_data:/var/lib/postgresql/data
      - ./src/main/webapp/WEB-INF/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  covoitme_data: