services:
  app:
    image: ollopic/covoitme:latest
    container_name: covoitme-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=covoitme
      - DB_USER=covoitme
      - DB_PASSWORD=password
    depends_on:
      - db
    volumes:
      - app-sql:/sql
    restart: always

  db:
    image: postgres:17.5
    container_name: covoitme-db
    environment:
      - POSTGRES_DB=covoitme
      - POSTGRES_USER=covoitme
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
      - app-sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

volumes:
  db-data:
  app-sql: